zuul:
  routes:
    user:
      path: /account/**
      service-id: User-Center-Service
      # 是否把前缀忽略掉，先不忽略
      strip-prefix: false
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    health-check:
      enabled: true
spring:
  application:
    name: netflix-zuul
management:
  security:
    # 暂时关闭安全检测，外网时不要禁掉！！！
    enabled: false